//
//  Data1.swift
//  Cmd
//
//  Created by Konstantin Zyrianov on 2021-11-23.
//

import Foundation

enum Command {
    case signal(UInt16)
    case just(String)
    case not(String)
    case andSignal(UInt16, String)
    case and(String, String)
    case or(String, String)
    case rshift(String, UInt16)
    case lshift(String, UInt16)
}

struct Item {
    let command: Command
    let target: String
}

let data1 = [
    Item(command: .signal(123), target: "x"),
    Item(command: .signal(456), target: "y"),
    Item(command: .and("x", "y"), target: "d"),
    Item(command: .or("x", "y"), target: "e"),
    Item(command: .lshift("x", 2), target: "f"),
    Item(command: .rshift("y", 2), target: "g"),
    Item(command: .not("x"), target: "h"),
    Item(command: .not("y"), target: "i"),
]

let data = [
    Item(command: .and("af", "ah"), target: "ai"),
    Item(command: .not("lk"), target: "ll"),
    Item(command: .rshift("hz", 1), target: "is"),
    Item(command: .not("go"), target: "gp"),
    Item(command: .or("du", "dt"), target: "dv"),
    Item(command: .rshift("x", 5), target: "aa"),
    Item(command: .or("at", "az"), target: "ba"),
    Item(command: .lshift("eo", 15), target: "es"),
    Item(command: .or("ci", "ct"), target: "cu"),
    Item(command: .rshift("b", 5), target: "f"),
    Item(command: .or("fm", "fn"), target: "fo"),
    Item(command: .not("ag"), target: "ah"),
    Item(command: .or("v", "w"), target: "x"),
    Item(command: .and("g", "i"), target: "j"),
    Item(command: .lshift("an", 15), target: "ar"),
    Item(command: .andSignal(1, "cx"), target: "cy"),
    Item(command: .and("jq", "jw"), target: "jy"),
    Item(command: .rshift("iu", 5), target: "ix"),
    Item(command: .and("gl", "gm"), target: "go"),
    Item(command: .not("bw"), target: "bx"),
    Item(command: .rshift("jp", 3), target: "jr"),
    Item(command: .and("hg", "hh"), target: "hj"),
    Item(command: .and("bv", "bx"), target: "by"),
    Item(command: .or("er", "es"), target: "et"),
    Item(command: .or("kl", "kr"), target: "ks"),
    Item(command: .rshift("et", 1), target: "fm"),
    Item(command: .and("e", "f"), target: "h"),
    Item(command: .lshift("u", 1), target: "ao"),
    Item(command: .rshift("he", 1), target: "hx"),
    Item(command: .and("eg", "ei"), target: "ej"),
    Item(command: .and("bo", "bu"), target: "bw"),
    Item(command: .or("dz", "ef"), target: "eg"),
    Item(command: .rshift("dy", 3), target: "ea"),
    Item(command: .or("gl", "gm"), target: "gn"),
    Item(command: .lshift("da", 1), target: "du"),
    Item(command: .or("au", "av"), target: "aw"),
    Item(command: .or("gj", "gu"), target: "gv"),
    Item(command: .or("eu", "fa"), target: "fb"),
    Item(command: .or("lg", "lm"), target: "ln"),
    Item(command: .or("e", "f"), target: "g"),
    Item(command: .not("dm"), target: "dn"),
    Item(command: .not("l"), target: "m"),
    Item(command: .or("aq", "ar"), target: "as"),
    Item(command: .rshift("gj", 5), target: "gm"),
    Item(command: .and("hm", "ho"), target: "hp"),
    Item(command: .lshift("ge", 15), target: "gi"),
    Item(command: .rshift("jp", 1), target: "ki"),
    Item(command: .or("hg", "hh"), target: "hi"),
    Item(command: .lshift("lc", 1), target: "lw"),
    Item(command: .or("km", "kn"), target: "ko"),
    Item(command: .lshift("eq", 1), target: "fk"),
    Item(command: .andSignal(1, "am"), target: "an"),
    Item(command: .rshift("gj", 1), target: "hc"),
    Item(command: .and("aj", "al"), target: "am"),
    Item(command: .and("gj", "gu"), target: "gw"),
    Item(command: .and("ko", "kq"), target: "kr"),
    Item(command: .or("ha", "gz"), target: "hb"),
    Item(command: .or("bn", "by"), target: "bz"),
    Item(command: .or("iv", "jb"), target: "jc"),
    Item(command: .not("ac"), target: "ad"),
    Item(command: .or("bo", "bu"), target: "bv"),
    Item(command: .and("d", "j"), target: "l"),
    Item(command: .lshift("bk", 1), target: "ce"),
    Item(command: .or("de", "dk"), target: "dl"),
    Item(command: .rshift("dd", 1), target: "dw"),
    Item(command: .and("hz", "ik"), target: "im"),
    Item(command: .not("jd"), target: "je"),
    Item(command: .rshift("fo", 2), target: "fp"),
    Item(command: .lshift("hb", 1), target: "hv"),
    Item(command: .rshift("lf", 2), target: "lg"),
    Item(command: .rshift("gj", 3), target: "gl"),
    Item(command: .or("ki", "kj"), target: "kk"),
    Item(command: .not("ak"), target: "al"),
    Item(command: .or("ld", "le"), target: "lf"),
    Item(command: .rshift("ci", 3), target: "ck"),
    Item(command: .andSignal(1, "cc"), target: "cd"),
    Item(command: .not("kx"), target: "ky"),
    Item(command: .or("fp", "fv"), target: "fw"),
    Item(command: .and("ev", "ew"), target: "ey"),
    Item(command: .lshift("dt", 15), target: "dx"),
    Item(command: .not("ax"), target: "ay"),
    Item(command: .and("bp", "bq"), target: "bs"),
    Item(command: .not("ii"), target: "ij"),
    Item(command: .and("ci", "ct"), target: "cv"),
    Item(command: .or("iq", "ip"), target: "ir"),
    Item(command: .rshift("x", 2), target: "y"),
    Item(command: .or("fq", "fr"), target: "fs"),
    Item(command: .rshift("bn", 5), target: "bq"),
    Item(command: .signal(0), target: "c"),
    Item(command: .signal(956), target: "b"),
    Item(command: .or("d", "j"), target: "k"),
    Item(command: .or("z", "aa"), target: "ab"),
    Item(command: .or("gf", "ge"), target: "gg"),
    Item(command: .or("df", "dg"), target: "dh"),
    Item(command: .not("hj"), target: "hk"),
    Item(command: .not("di"), target: "dj"),
    Item(command: .lshift("fj", 15), target: "fn"),
    Item(command: .rshift("lf", 1), target: "ly"),
    Item(command: .and("b", "n"), target: "p"),
    Item(command: .or("jq", "jw"), target: "jx"),
    Item(command: .and("gn", "gp"), target: "gq"),
    Item(command: .rshift("x", 1), target: "aq"),
    Item(command: .and("ex", "ez"), target: "fa"),
    Item(command: .not("fc"), target: "fd"),
    Item(command: .or("bj", "bi"), target: "bk"),
    Item(command: .rshift("as", 5), target: "av"),
    Item(command: .lshift("hu", 15), target: "hy"),
    Item(command: .not("gs"), target: "gt"),
    Item(command: .and("fs", "fu"), target: "fv"),
    Item(command: .and("dh", "dj"), target: "dk"),
    Item(command: .and("bz", "cb"), target: "cc"),
    Item(command: .rshift("dy", 1), target: "er"),
    Item(command: .or("hc", "hd"), target: "he"),
    Item(command: .or("fo", "fz"), target: "ga"),
    Item(command: .or("t", "s"), target: "u"),
    Item(command: .rshift("b", 2), target: "d"),
    Item(command: .not("jy"), target: "jz"),
    Item(command: .rshift("hz", 2), target: "ia"),
    Item(command: .and("kk", "kv"), target: "kx"),
    Item(command: .and("ga", "gc"), target: "gd"),
    Item(command: .lshift("fl", 1), target: "gf"),
    Item(command: .and("bn", "by"), target: "ca"),
    Item(command: .not("hr"), target: "hs"),
    Item(command: .not("bs"), target: "bt"),
    Item(command: .rshift("lf", 3), target: "lh"),
    Item(command: .and("au", "av"), target: "ax"),
    Item(command: .andSignal(1, "gd"), target: "ge"),
    Item(command: .or("jr", "js"), target: "jt"),
    Item(command: .and("fw", "fy"), target: "fz"),
    Item(command: .not("iz"), target: "ja"),
    Item(command: .lshift("c", 1), target: "t"),
    Item(command: .rshift("dy", 5), target: "eb"),
    Item(command: .or("bp", "bq"), target: "br"),
    Item(command: .not("h"), target: "i"),
    Item(command: .andSignal(1, "ds"), target: "dt"),
    Item(command: .and("ab", "ad"), target: "ae"),
    Item(command: .lshift("ap", 1), target: "bj"),
    Item(command: .and("br", "bt"), target: "bu"),
    Item(command: .not("ca"), target: "cb"),
    Item(command: .not("el"), target: "em"),
    Item(command: .lshift("s", 15), target: "w"),
    Item(command: .or("gk", "gq"), target: "gr"),
    Item(command: .and("ff", "fh"), target: "fi"),
    Item(command: .lshift("kf", 15), target: "kj"),
    Item(command: .and("fp", "fv"), target: "fx"),
    Item(command: .or("lh", "li"), target: "lj"),
    Item(command: .rshift("bn", 3), target: "bp"),
    Item(command: .or("jp", "ka"), target: "kb"),
    Item(command: .or("lw", "lv"), target: "lx"),
    Item(command: .and("iy", "ja"), target: "jb"),
    Item(command: .or("dy", "ej"), target: "ek"),
    Item(command: .andSignal(1, "bh"), target: "bi"),
    Item(command: .not("kt"), target: "ku"),
    Item(command: .or("ao", "an"), target: "ap"),
    Item(command: .and("ia", "ig"), target: "ii"),
    Item(command: .not("ey"), target: "ez"),
    Item(command: .rshift("bn", 1), target: "cg"),
    Item(command: .or("fk", "fj"), target: "fl"),
    Item(command: .or("ce", "cd"), target: "cf"),
    Item(command: .and("eu", "fa"), target: "fc"),
    Item(command: .or("kg", "kf"), target: "kh"),
    Item(command: .and("jr", "js"), target: "ju"),
    Item(command: .rshift("iu", 3), target: "iw"),
    Item(command: .and("df", "dg"), target: "di"),
    Item(command: .and("dl", "dn"), target: "do"),
    Item(command: .lshift("la", 15), target: "le"),
    Item(command: .rshift("fo", 1), target: "gh"),
    Item(command: .not("gw"), target: "gx"),
    Item(command: .not("gb"), target: "gc"),
    Item(command: .lshift("ir", 1), target: "jl"),
    Item(command: .and("x", "ai"), target: "ak"),
    Item(command: .rshift("he", 5), target: "hh"),
    Item(command: .andSignal(1, "lu"), target: "lv"),
    Item(command: .not("ft"), target: "fu"),
    Item(command: .or("gh", "gi"), target: "gj"),
    Item(command: .rshift("lf", 5), target: "li"),
    Item(command: .rshift("x", 3), target: "z"),
    Item(command: .rshift("b", 3), target: "e"),
    Item(command: .rshift("he", 2), target: "hf"),
    Item(command: .not("fx"), target: "fy"),
    Item(command: .and("jt", "jv"), target: "jw"),
    Item(command: .or("hx", "hy"), target: "hz"),
    Item(command: .and("jp", "ka"), target: "kc"),
    Item(command: .and("fb", "fd"), target: "fe"),
    Item(command: .or("hz", "ik"), target: "il"),
    Item(command: .rshift("ci", 1), target: "db"),
    Item(command: .and("fo", "fz"), target: "gb"),
    Item(command: .and("fq", "fr"), target: "ft"),
    Item(command: .rshift("gj", 2), target: "gk"),
    Item(command: .or("cg", "ch"), target: "ci"),
    Item(command: .lshift("cd", 15), target: "ch"),
    Item(command: .lshift("jm", 1), target: "kg"),
    Item(command: .and("ih", "ij"), target: "ik"),
    Item(command: .rshift("fo", 3), target: "fq"),
    Item(command: .rshift("fo", 5), target: "fr"),
    Item(command: .andSignal(1, "fi"), target: "fj"),
    Item(command: .andSignal(1, "kz"), target: "la"),
    Item(command: .and("iu", "jf"), target: "jh"),
    Item(command: .and("cq", "cs"), target: "ct"),
    Item(command: .lshift("dv", 1), target: "ep"),
    Item(command: .or("hf", "hl"), target: "hm"),
    Item(command: .and("km", "kn"), target: "kp"),
    Item(command: .and("de", "dk"), target: "dm"),
    Item(command: .rshift("dd", 5), target: "dg"),
    Item(command: .not("lo"), target: "lp"),
    Item(command: .not("ju"), target: "jv"),
    Item(command: .not("fg"), target: "fh"),
    Item(command: .and("cm", "co"), target: "cp"),
    Item(command: .and("ea", "eb"), target: "ed"),
    Item(command: .rshift("dd", 3), target: "df"),
    Item(command: .and("gr", "gt"), target: "gu"),
    Item(command: .or("ep", "eo"), target: "eq"),
    Item(command: .and("cj", "cp"), target: "cr"),
    Item(command: .or("lf", "lq"), target: "lr"),
    Item(command: .lshift("gg", 1), target: "ha"),
    Item(command: .rshift("et", 2), target: "eu"),
    Item(command: .not("jh"), target: "ji"),
    Item(command: .and("ek", "em"), target: "en"),
    Item(command: .lshift("jk", 15), target: "jo"),
    Item(command: .or("ia", "ig"), target: "ih"),
    Item(command: .and("gv", "gx"), target: "gy"),
    Item(command: .and("et", "fe"), target: "fg"),
    Item(command: .and("lh", "li"), target: "lk"),
    Item(command: .andSignal(1, "io"), target: "ip"),
    Item(command: .and("kb", "kd"), target: "ke"),
    Item(command: .rshift("kk", 5), target: "kn"),
    Item(command: .and("id", "if"), target: "ig"),
    Item(command: .not("ls"), target: "lt"),
    Item(command: .or("dw", "dx"), target: "dy"),
    Item(command: .and("dd", "do"), target: "dq"),
    Item(command: .and("lf", "lq"), target: "ls"),
    Item(command: .not("kc"), target: "kd"),
    Item(command: .and("dy", "ej"), target: "el"),
    Item(command: .andSignal(1, "ke"), target: "kf"),
    Item(command: .or("et", "fe"), target: "ff"),
    Item(command: .rshift("hz", 5), target: "ic"),
    Item(command: .or("dd", "do"), target: "dp"),
    Item(command: .or("cj", "cp"), target: "cq"),
    Item(command: .not("dq"), target: "dr"),
    Item(command: .rshift("kk", 1), target: "ld"),
    Item(command: .and("jg", "ji"), target: "jj"),
    Item(command: .or("he", "hp"), target: "hq"),
    Item(command: .and("hi", "hk"), target: "hl"),
    Item(command: .and("dp", "dr"), target: "ds"),
    Item(command: .and("dz", "ef"), target: "eh"),
    Item(command: .rshift("hz", 3), target: "ib"),
    Item(command: .or("db", "dc"), target: "dd"),
    Item(command: .lshift("hw", 1), target: "iq"),
    Item(command: .and("he", "hp"), target: "hr"),
    Item(command: .not("cr"), target: "cs"),
    Item(command: .and("lg", "lm"), target: "lo"),
    Item(command: .or("hv", "hu"), target: "hw"),
    Item(command: .and("il", "in"), target: "io"),
    Item(command: .not("eh"), target: "ei"),
    Item(command: .lshift("gz", 15), target: "hd"),
    Item(command: .and("gk", "gq"), target: "gs"),
    Item(command: .andSignal(1, "en"), target: "eo"),
    Item(command: .not("kp"), target: "kq"),
    Item(command: .rshift("et", 5), target: "ew"),
    Item(command: .and("lj", "ll"), target: "lm"),
    Item(command: .rshift("he", 3), target: "hg"),
    Item(command: .rshift("et", 3), target: "ev"),
    Item(command: .and("as", "bd"), target: "bf"),
    Item(command: .and("cu", "cw"), target: "cx"),
    Item(command: .and("jx", "jz"), target: "ka"),
    Item(command: .or("b", "n"), target: "o"),
    Item(command: .and("be", "bg"), target: "bh"),
    Item(command: .andSignal(1, "ht"), target: "hu"),
    Item(command: .andSignal(1, "gy"), target: "gz"),
    Item(command: .not("hn"), target: "ho"),
    Item(command: .or("ck", "cl"), target: "cm"),
    Item(command: .and("ec", "ee"), target: "ef"),
    Item(command: .lshift("lv", 15), target: "lz"),
    Item(command: .and("ks", "ku"), target: "kv"),
    Item(command: .not("ie"), target: "if"),
    Item(command: .and("hf", "hl"), target: "hn"),
    Item(command: .andSignal(1, "r"), target: "s"),
    Item(command: .and("ib", "ic"), target: "ie"),
    Item(command: .and("hq", "hs"), target: "ht"),
    Item(command: .and("y", "ae"), target: "ag"),
    Item(command: .not("ed"), target: "ee"),
    Item(command: .lshift("bi", 15), target: "bm"),
    Item(command: .rshift("dy", 2), target: "dz"),
    Item(command: .rshift("ci", 2), target: "cj"),
    Item(command: .not("bf"), target: "bg"),
    Item(command: .not("im"), target: "in"),
    Item(command: .or("ev", "ew"), target: "ex"),
    Item(command: .or("ib", "ic"), target: "id"),
    Item(command: .rshift("bn", 2), target: "bo"),
    Item(command: .rshift("dd", 2), target: "de"),
    Item(command: .or("bl", "bm"), target: "bn"),
    Item(command: .rshift("as", 1), target: "bl"),
    Item(command: .or("ea", "eb"), target: "ec"),
    Item(command: .and("ln", "lp"), target: "lq"),
    Item(command: .rshift("kk", 3), target: "km"),
    Item(command: .or("is", "it"), target: "iu"),
    Item(command: .rshift("iu", 2), target: "iv"),
    Item(command: .or("as", "bd"), target: "be"),
    Item(command: .lshift("ip", 15), target: "it"),
    Item(command: .or("iw", "ix"), target: "iy"),
    Item(command: .rshift("kk", 2), target: "kl"),
    Item(command: .not("bb"), target: "bc"),
    Item(command: .rshift("ci", 5), target: "cl"),
    Item(command: .or("ly", "lz"), target: "ma"),
    Item(command: .and("z", "aa"), target: "ac"),
    Item(command: .rshift("iu", 1), target: "jn"),
    Item(command: .lshift("cy", 15), target: "dc"),
    Item(command: .lshift("cf", 1), target: "cz"),
    Item(command: .rshift("as", 3), target: "au"),
    Item(command: .or("cz", "cy"), target: "da"),
    Item(command: .and("kw", "ky"), target: "kz"),
    Item(command: .just("lx"), target: "a"),
    Item(command: .and("iw", "ix"), target: "iz"),
    Item(command: .and("lr", "lt"), target: "lu"),
    Item(command: .rshift("jp", 5), target: "js"),
    Item(command: .and("aw", "ay"), target: "az"),
    Item(command: .and("jc", "je"), target: "jf"),
    Item(command: .or("lb", "la"), target: "lc"),
    Item(command: .not("cn"), target: "co"),
    Item(command: .lshift("kh", 1), target: "lb"),
    Item(command: .andSignal(1, "jj"), target: "jk"),
    Item(command: .or("y", "ae"), target: "af"),
    Item(command: .and("ck", "cl"), target: "cn"),
    Item(command: .or("kk", "kv"), target: "kw"),
    Item(command: .not("cv"), target: "cw"),
    Item(command: .and("kl", "kr"), target: "kt"),
    Item(command: .or("iu", "jf"), target: "jg"),
    Item(command: .and("at", "az"), target: "bb"),
    Item(command: .rshift("jp", 2), target: "jq"),
    Item(command: .and("iv", "jb"), target: "jd"),
    Item(command: .or("jn", "jo"), target: "jp"),
    Item(command: .or("x", "ai"), target: "aj"),
    Item(command: .and("ba", "bc"), target: "bd"),
    Item(command: .or("jl", "jk"), target: "jm"),
    Item(command: .rshift("b", 1), target: "v"),
    Item(command: .and("o", "q"), target: "r"),
    Item(command: .not("p"), target: "q"),
    Item(command: .and("k", "m"), target: "n"),
    Item(command: .rshift("as", 2), target: "at"),
]
